version: '0.1.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: choco install opencover.portable
  - cmd: choco install codecov
build_script:
  - cmd: dotnet build ./src
after_build:
  # For once the build has completed
clone_depth: 1
test_script:
  - cmd: dotnet test .\src\Holo.Except.Test\
  - cmd: OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test ./src/Holo.Except.Test" -output:".\HoloExcept_coverage.xml" -oldstyle
  - cmd: codecov -f "HoloExcept_coverage.xml" -t e3eea377-ce95-4f9f-9baa-387d22422c37
deploy: off